#!/bin/bash

NP=20

(cd components && ./prepareMesh)
(cd runCase && ./run.pre && rm -rf processor* && decomposePar -allRegions)
(cd runCase && mpirun -np $NP multiCoastFoam -parallel | tee solve.log)

#reconstructPar -allRegions
