#!/bin/bash

NP=8

(cd components && ./prepareTsunamiMesh)
(cd tsunamiCase && ./run.pre && rm -rf processor* && decomposePar -allRegions)
(cd tsunamiCase && mpirun -np $NP multiPhysicsSWInterFoam -parallel | tee solve.log)

#reconstructPar -allRegions
