#!/bin/bash

NP=8

(cd components && ./prepareBaseMesh && ./prepareFreeFloatMesh)
(cd freeFloatCase && ./run.pre && rm -rf processor* && decomposePar -allRegions)
(cd freeFloatCase && mpirun -np $NP multiCoastFoam -parallel | tee solve.log)

#reconstructPar -allRegions
