#!/bin/bash
# Allwmake - build all components

wmake $* csvFunctions

wmake $* SWWaveSource

wmake $* regionConnector

wmake $* SWRiemannSolver

wmake $* bulletOverset

wmake $* ThirdParty/BulletSrc/LinearMath
wmake $* ThirdParty/BulletSrc/BulletCollision
wmake $* ThirdParty/BulletSrc/BulletDynamics

if [ -d "ThirdParty/MoorDynSrc" ]; then
    requiredDirs=("Eigen" "Util" "Waves")
    missing=0

    for dir in "${requiredDirs[@]}"; do
        if [ ! -d "ThirdParty/MoorDynSrc/$dir" ]; then
            echo "Missing required directory: $dir"
            missing=1
        fi
    done

    if [ "$missing" -eq 1 ]; then
        echo "Cleaning folder (preserving Make/) and re-downloading..."

        find ThirdParty/MoorDynSrc -mindepth 1 -not -path "ThirdParty/MoorDynSrc/Make*" -exec rm -rf {} +

        pushd ThirdParty/MoorDynSrc > /dev/null

        git init
        git remote add origin https://github.com/FloatingArrayDesign/MoorDyn.git
        git config core.sparseCheckout true
        echo "source" >> .git/info/sparse-checkout
        git pull origin master

        mv source/* ./
        rm -r source

        popd > /dev/null
    fi
fi

wmake $* ThirdParty/MoorDynSrc

wmake $* physicsManager/bulletWorld
wmake $* physicsManager/moorDynWorld

wmake $* physicsManager
